### PR TITLE
fix mmTensorCheck by adding a fixpoint on nat simplification

### PR DESCRIPTION
**Pull request by Bastacyclop**

### CODE REVIEW

**Comment by Bastacyclop** [comment]
uses https://github.com/rise-lang/arithexpr/pull/16

**Review by michel-steuwer — APPROVED** [review]
👍

**Comment by michel-steuwer** [comment]
I will check the `arithexpr` PR as well.

**Comment by michel-steuwer** [comment]
I merged rise-lang/arithexpr#16

**Pull request merged**
